def test2024():
    assert main.gen_cal(2024, 1) == [
        'C1FMXJVSDLMXJVSDLMXJVSDLMXJVSDLMX',
        'C2JVSDLMXJVSDLMXJVSDLMXJVSDLMXJ--',
        'C3VSDLMXJVSDLMXJVSDLMXJVSDLMXJVSD',
        'C4LMXJVSDLMXJVSDLMXJVSDLMXJVSDLM-',
        'C5XJVSDLMXJVSDLMXJVSDLMXJVSDLMXJV',
        'C6SDLMXJVSDLMXJVSDLMXJVSDLMXJVSD-',
        'C7LMXJVSDLMXJVSDLMXJVSDLMXJVSDLMX',
        'C8JVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS',
        'C9DLMXJVSDLMXJVSDLMXJVSDLMXJVSDL-',
        'CAMXJVSDLMXJVSDLMXJVSDLMXJVSDLMXJ',
        'CBVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS-',
        'CCDLMXJVSDLMXJVSDLMXJVSDLMFJVSDLM'
    ]


def test2425():
    assert main.gen_cal(2024, 7) == [
        'C7LMXJVSDLMXJVSDLMXJVSDLMXJVSDLMX',
        'C8JVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS',
        'C9DLMXJVSDLMXJVSDLMXJVSDLMXJVSDL-',
        'CAMXJVSDLMXJVSDLMXJVSDLMXJVSDLMXJ',
        'CBVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS-',
        'CCDLMXJVSDLMXJVSDLMXJVSDLMFJVSDLM',
        'C1XJVSDLMXJVSDLMXJVSDLMXJVSDLMXJV',
        'C2SDLMXJVSDLMXJVSDLMXJVSDLMXJV---',
        'C3SDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL',
        'C4MXJVSDLMXJVSDLMXJVSDLMXJVSDLMX-',
        'C5JVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS',
        'C6DLMXJVSDLMXJVSDLMXJVSDLMXJVSDL-'
    ]
