from logic import gen_cal

fest = [
    {"st": "2020-01-01", "ed": "2020-01-07"},
    {"st": "2020-02-28", "ed": "2020-02-28"},
    {"st": "2020-12-25", "ed": "2021-01-07"}
]


def test_full_year():
    assert gen_cal(2020, 1, fest) == [
        'C1FFFFFFFXJVSDLMXJVSDLMXJVSDLMXJV',
        'C2SDLMXJVSDLMXJVSDLMXJVSDLMXJFS--',
        'C3DLMXJVSDLMXJVSDLMXJVSDLMXJVSDLM',
        'C4XJVSDLMXJVSDLMXJVSDLMXJVSDLMXJ-',
        'C5VSDLMXJVSDLMXJVSDLMXJVSDLMXJVSD',
        'C6LMXJVSDLMXJVSDLMXJVSDLMXJVSDLM-',
        'C7XJVSDLMXJVSDLMXJVSDLMXJVSDLMXJV',
        'C8SDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL',
        'C9MXJVSDLMXJVSDLMXJVSDLMXJVSDLMX-',
        'CAJVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS',
        'CBDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL-',
        'CCMXJVSDLMXJVSDLMXJVSDLMXJFFFFFFF'
    ]


def test_part_year():
    assert gen_cal(2020, 7, fest) == [
        'C7XJVSDLMXJVSDLMXJVSDLMXJVSDLMXJV',
        'C8SDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL',
        'C9MXJVSDLMXJVSDLMXJVSDLMXJVSDLMX-',
        'CAJVSDLMXJVSDLMXJVSDLMXJVSDLMXJVS',
        'CBDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL-',
        'CCMXJVSDLMXJVSDLMXJVSDLMXJFFFFFFF',
        'C1FFFFFFFVSDLMXJVSDLMXJVSDLMXJVSD',
        'C2LMXJVSDLMXJVSDLMXJVSDLMXJVSD---',
        'C3LMXJVSDLMXJVSDLMXJVSDLMXJVSDLMX',
        'C4JVSDLMXJVSDLMXJVSDLMXJVSDLMXJV-',
        'C5SDLMXJVSDLMXJVSDLMXJVSDLMXJVSDL',
        'C6MXJVSDLMXJVSDLMXJVSDLMXJVSDLMX-'
    ]
